var GROK_BOT_SESSION_KIND_MAIN = "main";
var GROK_BOT_SESSION_KIND_SLACK_DM = "slack_dm";
var GROK_BOT_SESSION_KIND_SLACK_GROUP_DM = "slack_group_dm";
var GROK_BOT_SESSION_KIND_SLACK_THREAD = "slack_thread";
var GROK_BOT_SESSION_KIND_DM = "dm";
var GROK_BOT_SESSION_KIND_GROUP = "group";
