var import_node_net = require("node:net");
var COMMON_PUBLIC_GTLDS = /* @__PURE__ */ new Set([
  "app",
  "biz",
  "blog",
  "cloud",
  "com",
  "dev",
  "edu",
  "email",
  "fun",
  "gov",
  "info",
  "int",
  "live",
  "media",
  "mil",
  "net",
  "news",
  "online",
  "org",
  "shop",
  "site",
  "social",
  "space",
  "store",
  "tech",
  "top",
  "wiki",
  "work",
  "world",
  "xyz"
]);
var DELEGATED_CC_TLDS = /* @__PURE__ */ new Set([
  "ac",
  "ad",
  "ae",
  "af",
  "ag",
  "ai",
  "al",
  "am",
  "ao",
  "aq",
  "ar",
  "as",
  "at",
  "au",
  "aw",
  "ax",
  "az",
  "ba",
  "bb",
  "bd",
  "be",
  "bf",
  "bg",
  "bh",
  "bi",
  "bj",
  "bm",
  "bn",
  "bo",
  "br",
  "bs",
  "bt",
  "bw",
  "by",
  "bz",
  "ca",
  "cc",
  "cd",
  "cf",
  "cg",
  "ch",
  "ci",
  "ck",
  "cl",
  "cm",
  "cn",
  "co",
  "cr",
  "cu",
  "cv",
  "cw",
  "cx",
  "cy",
  "cz",
  "de",
  "dj",
  "dk",
  "dm",
  "do",
  "dz",
  "ec",
  "ee",
  "eg",
  "er",
  "es",
  "et",
  "eu",
  "fi",
  "fj",
  "fk",
  "fm",
  "fo",
  "fr",
  "ga",
  "gd",
  "ge",
  "gf",
  "gg",
  "gh",
  "gi",
  "gl",
  "gm",
  "gn",
  "gp",
  "gq",
  "gr",
  "gs",
  "gt",
  "gu",
  "gw",
  "gy",
  "hk",
  "hm",
  "hn",
  "hr",
  "ht",
  "hu",
  "id",
  "ie",
  "il",
  "im",
  "in",
  "io",
  "iq",
  "ir",
  "is",
  "it",
  "je",
  "jm",
  "jo",
  "jp",
  "ke",
  "kg",
  "kh",
  "ki",
  "km",
  "kn",
  "kp",
  "kr",
  "kw",
  "ky",
  "kz",
  "la",
  "lb",
  "lc",
  "li",
  "lk",
  "lr",
  "ls",
  "lt",
  "lu",
  "lv",
  "ly",
  "ma",
  "mc",
  "md",
  "me",
  "mg",
  "mh",
  "mk",
  "ml",
  "mm",
  "mn",
  "mo",
  "mp",
  "mq",
  "mr",
  "ms",
  "mt",
  "mu",
  "mv",
  "mw",
  "mx",
  "my",
  "mz",
  "na",
  "nc",
  "ne",
  "nf",
  "ng",
  "ni",
  "nl",
  "no",
  "np",
  "nr",
  "nu",
  "nz",
  "om",
  "pa",
  "pe",
  "pf",
  "pg",
  "ph",
  "pk",
  "pl",
  "pm",
  "pn",
  "pr",
  "ps",
  "pt",
  "pw",
  "py",
  "qa",
  "re",
  "ro",
  "rs",
  "ru",
  "rw",
  "sa",
  "sb",
  "sc",
  "sd",
  "se",
  "sg",
  "sh",
  "si",
  "sk",
  "sl",
  "sm",
  "sn",
  "so",
  "sr",
  "ss",
  "st",
  "su",
  "sv",
  "sx",
  "sy",
  "sz",
  "tc",
  "td",
  "tf",
  "tg",
  "th",
  "tj",
  "tk",
  "tl",
  "tm",
  "tn",
  "to",
  "tr",
  "tt",
  "tv",
  "tw",
  "tz",
  "ua",
  "ug",
  "uk",
  "us",
  "uy",
  "uz",
  "va",
  "vc",
  "ve",
  "vg",
  "vi",
  "vn",
  "vu",
  "wf",
  "ws",
  "ye",
  "yt",
  "za",
  "zm",
  "zw"
]);
var CC_SECOND_LEVEL_LABELS = /* @__PURE__ */ new Set([
  "ac",
  "co",
  "com",
  "edu",
  "go",
  "gov",
  "mil",
  "ne",
  "net",
  "or",
  "org",
  "sch"
]);
var PRIVATE_TLDS = /* @__PURE__ */ new Set([
  "alt",
  "corp",
  "example",
  "home",
  "internal",
  "intranet",
  "invalid",
  "lan",
  "local",
  "mail",
  "onion",
  "private",
  "test"
]);
var MAX_BUCKET_LENGTH = 100;
function mint(bucket) {
  return bucket;
}
function boundedSiteBucket(hostname3) {
  const host = hostname3.toLowerCase().replace(/\.$/, "");
  if (host.startsWith("[") || (0, import_node_net.isIP)(host) !== 0) return mint("ip");
  if (host === "localhost" || host.endsWith(".localhost")) return mint("local");
  const labels = host.split(".");
  if (labels.length < 2) return mint("private");
  const tld = labels[labels.length - 1] ?? "";
  if (PRIVATE_TLDS.has(tld)) return mint("private");
  const isCcTld = DELEGATED_CC_TLDS.has(tld);
  if (!isCcTld && !COMMON_PUBLIC_GTLDS.has(tld)) return mint("private");
  const secondLevel = labels[labels.length - 2] ?? "";
  const registrableLabels = isCcTld && CC_SECOND_LEVEL_LABELS.has(secondLevel) ? 3 : 2;
  const bucket = labels.slice(-registrableLabels).join(".");
  return bucket.length > MAX_BUCKET_LENGTH ? mint("private") : mint(bucket);
}
var SITE_SECTIONS_BY_BUCKET = /* @__PURE__ */ new Map([
  ["airbnb.com", { rest: "airbnb" }],
  ["bestbuy.com", { rest: "bestbuy" }],
  ["costco.com", { rest: "costco" }],
  ["craigslist.org", { rest: "craigslist" }],
  ["doordash.com", { rest: "doordash" }],
  ["ebay.com", { rest: "ebay" }],
  ["etsy.com", { rest: "etsy" }],
  ["expedia.com", { rest: "expedia" }],
  [
    "facebook.com",
    {
      rules: [{ kind: "path", prefix: "/marketplace", section: "facebook_marketplace" }],
      rest: "facebook"
    }
  ],
  ["fedex.com", { rest: "fedex" }],
  [
    "google.com",
    {
      rules: [
        { kind: "path", prefix: "/travel/flights", section: "google_flights" },
        { kind: "subdomain", label: "flights", section: "google_flights" },
        { kind: "path", prefix: "/maps", section: "google_maps" },
        { kind: "subdomain", label: "maps", section: "google_maps" }
      ],
      rest: "google_search"
    }
  ],
  ["instacart.com", { rest: "instacart" }],
  ["irs.gov", { rest: "irs" }],
  ["linkedin.com", { rest: "linkedin" }],
  ["luma.com", { rest: "luma" }],
  ["realtor.com", { rest: "realtor" }],
  ["resy.com", { rest: "resy" }],
  ["southwest.com", { rest: "southwest" }],
  ["target.com", { rest: "target" }],
  ["united.com", { rest: "united" }],
  ["ups.com", { rest: "ups" }],
  ["usps.com", { rest: "usps" }],
  ["yelp.com", { rest: "yelp" }]
]);
function siteSectionForUrl(url2) {
  const bucket = boundedSiteBucket(url2.hostname);
  const sections = SITE_SECTIONS_BY_BUCKET.get(bucket);
  if (sections === void 0) return "other";
  const host = url2.hostname.toLowerCase().replace(/\.$/, "");
  for (const rule of sections.rules ?? []) {
    const matches = rule.kind === "path" ? url2.pathname === rule.prefix || url2.pathname.startsWith(`${rule.prefix}/`) : host === `${rule.label}.${bucket}`;
    if (matches) return rule.section;
  }
  return sections.rest;
}
function visitedSiteBucket(rawUrl) {
  if (!URL.canParse(rawUrl)) return void 0;
  const hostname3 = new URL(rawUrl).hostname;
  return hostname3.length === 0 ? void 0 : boundedSiteBucket(hostname3);
}
function withSiteVisitTracking(auditor, onVisit, lookupSigned = () => void 0, lookupWallEpisode = () => void 0) {
  return {
    record: (record2) => {
      auditor.record(record2);
      if (record2.action.kind !== "browserNavigation") return;
      if (!URL.canParse(record2.action.url)) return;
      const url2 = new URL(record2.action.url);
      if (url2.hostname.length === 0) return;
      const signed = lookupSigned(url2.origin);
      const wallEpisodeId = lookupWallEpisode(record2);
      onVisit(
        {
          siteBucket: boundedSiteBucket(url2.hostname),
          siteSection: siteSectionForUrl(url2),
          ...signed === void 0 ? {} : { webBotAuthSigned: signed },
          ...wallEpisodeId === void 0 ? {} : { wallEpisodeId }
        },
        record2
      );
    }
  };
}
