var GROK_BOT_PLAN_LABEL = "Grok Bot Plan";
var ON_DEMAND_PAYMENT_METHOD_SETUP_ACTION = "startOnDemandPaymentMethodSetup";
var SUPPORTED_DASHBOARD_ACTIONS = /* @__PURE__ */ new Set([
  ...SAND_DASHBOARD_ACTION_VERBS,
  ON_DEMAND_PAYMENT_METHOD_SETUP_ACTION
]);
