var hostExtensionRegistry = [
  notificationsExtension,
  contentSearchExtension,
  credentialProviderExtension,
  memoryExtension,
  stateBackstopExtension,
  sourceMapExtension,
  telemetryExtension,
  traysExtension,
  authExtension,
  privacyModeExtension,
  experimentsExtension,
  browserUaExtension,
  inferenceExtension,
  localExecExtension,
  localToolPermissionExtension,
  attachmentsExtension,
  foreverBoxExtension,
  secretsExtension,
  turnExecutionExtension,
  transcriptExtension,
  transcriptPublishExtension,
  serverAgentProxyExtension,
  feedbackExtension,
  sessionExtension,
  automationsExtension,
  settingsExtension,
  boxLifecycleExtension,
  managedSetupExtension,
  mcpExtension,
  boxStoreSyncExtension,
  cloudAgentsExtension,
  agentIdentityExtension,
  resumeOwnershipExtension,
  actionAuditExtension,
  hostUpgradeExtension,
  autoReviewExtension,
  codebaseTelemetryExtension,
  teachRecordingExtension,
  webauthnProxyExtension,
  notifyBusExtension,
  wallpaperExtension,
  chromeCookieImportExtension,
  cookieOriginApprovalExtension,
  credentialFillExtension,
  botTemplateShareExtension,
  remoteAgentMessagingExtension,
  userFormVaultExtension,
  workingStateExportExtension,
  teamAdminPolicyExtension,
  messagesGrantsExtension,
  userSkillsCacheExtension,
  cycleUsageExtension,
  emailExtension,
  boxTimezoneExtension
];
async function startHostPluginRegistry(options2) {
  const { host, startTimeoutMs } = options2;
  const started2 = await startHostExtensions({
    extensions: hostExtensionRegistry,
    host,
    startTimeoutMs,
    onStopFailure: (extensionId, error42) => host.log(`host extension "${extensionId}" failed to stop: ${errorLogTag(error42)}`)
  });
  return {
    order: started2.order,
    api: (id) => started2.apis[id],
    stop: () => started2.stop()
  };
}
